search for artifacts that contain a given class
mthmulders/mcs pull request #35
Opened 2022-01-14 22:06 UTC by maddingo

2022-01-18 19:08 UTC, mthmulders requested changes
Thanks - again! - for your contribution and your patience. I do like some of the ideas you've introduced around the `SearchQuery` interface and its implementations, but there are also a few things I'd like to give another thought.

I can't yet say how that will turn out. How about if I have an idea before this PR is merged, we will solve it in this PR - otherwise I'll refactor it myself later?

2022-01-18 19:08 UTC, mthmulders commented on src/test/java/it/mulders/mcs/search/WildcardSearchQueryTest.java
> +        void simple_query_should_return_wildcard_query() {
I like this method name: very clear as to what you can expect the test to verify :-)

2022-01-18 19:08 UTC, mthmulders commented on src/main/java/it/mulders/mcs/search/SearchQuery.java
> +                    return new WildcardSearchQuery(query, limit != null ? limit : 1);
```suggestion
                    return new WildcardSearchQuery(query, limit != null ? limit : Constants.DEFAULT_MAX_SEARCH_RESULTS);
```

2022-01-18 19:53 UTC, mthmulders commented on src/main/java/it/mulders/mcs/cli/Cli.java
> +                paramLabel = "<count>"
I think it makes sense to have the `"-l" / "--last"` parameter for class-name search, too?

2022-01-19 07:41 UTC, mthmulders commented
I gave it a bit of thought. Again, I like the idea of the `SearchQuery` interface and having a builder for it. What I think I'd like to improve is two things

- the builder now knows everything about all types of search queries. I think I'd rather pull that apart into separate builders for each type of query
- the two queries for class-search are almost identical. I think I'd rather merge them.

If you want to, I can create a pull request against your branch, so you can evaluate what you think of these ideas?

2022-01-21 19:07 UTC, maddingo commented
Hi Maarten,
you go ahead and pull it apart as much as you like. I wasn't sure how to do
it properly in the spirit of the project. I tried though. I am glad you
like some of the ideas. Just use them at your leisure.
The class search and the full-class search are almost identical, 'c:' vs.
'fc:'. 'fc:' is very useful, e.g. if you go from J2EE to spring-boot and
have to find the artifact that contains a missing class.
Thanks for putting this tool in sdkman.
--
Martin


On Wed, Jan 19, 2022 at 8:41 AM Maarten Mulders ***@***.***>
wrote:

> I gave it a bit of thought. Again, I like the idea of the SearchQuery
> interface and having a builder for it. What I think I'd like to improve is
> two things
>
>    - the builder now knows everything about all types of search queries.
>    I think I'd rather pull that apart into separate builders for each type of
>    query
>    - the two queries for class-search are almost identical. I think I'd
>    rather merge them.
>
> If you want to, I can create a pull request against your branch, so you
> can evaluate what you think of these ideas?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mthmulders/mcs/pull/35#issuecomment-1016164522>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACYNCBRIVLA5JIUS75YRITUWZTKDANCNFSM5L73NCKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-22 19:25 UTC, mthmulders commented
> you go ahead and pull it apart as much as you like. I wasn't sure how to do it properly in the spirit of the project. I tried though. I am glad you like some of the ideas. Just use them at your leisure.

I definitely like the idea and look forward to including it in the project. Are you suggesting I take the feature from here and blend it into the code base?

> The class search and the full-class search are almost identical, 'c:' vs. 'fc:'. 'fc:' is very useful, e.g. if you go from J2EE to spring-boot and have to find the artifact that contains a missing class.

That's a good use case, I wouldn't even have thought of that. The same probably applies if you go from `javax.*` to `jakarta.*` namespaces.

> Thanks for putting this tool in sdkman.

You're welcome! Glad you find it useful.

2022-01-24 14:28 UTC, maddingo commented
Hi Maarten,
yes, just take what you need and blend it into your code. Don't bother with
attribution or anything. It is all yours. The best is probably to reject
the PR after you have taken what you need. Sorry for not being more
cooperative.

Martin


On Sat, Jan 22, 2022 at 8:26 PM Maarten Mulders ***@***.***>
wrote:

> you go ahead and pull it apart as much as you like. I wasn't sure how to
> do it properly in the spirit of the project. I tried though. I am glad you
> like some of the ideas. Just use them at your leisure.
>
> I definitely like the idea and look forward to including it in the
> project. Are you suggesting I take the feature from here and blend it into
> the code base?
>
> The class search and the full-class search are almost identical, 'c:' vs.
> 'fc:'. 'fc:' is very useful, e.g. if you go from J2EE to spring-boot and
> have to find the artifact that contains a missing class.
>
> That's a good use case, I wouldn't even have thought of that. The same
> probably applies if you go from javax.* to jakarta.* namespaces.
>
> Thanks for putting this tool in sdkman.
>
> You're welcome! Glad you find it useful.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mthmulders/mcs/pull/35#issuecomment-1019343442>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACYNCADS2QPNCX6BUQ6G6LUXMAE7ANCNFSM5L73NCKA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-24 19:14 UTC, mthmulders commented
> Sorry for not being more cooperative.

Not to worry. I appreciate the idea for this feature, I appreciate the effort you took in figuring out the API for it, and I appreciate the ideas you gave for refactoring!

> Yes, just take what you need and blend it into your code.

I'll take it from here.

2022-01-25 20:11 UTC, closed without merging